### ISSUE TITLE
format readme.md

### ISSUE THREAD

**Issue by DeanGadberry** [nctcstem/nctcstem.github.io#4]
The README.md needs to be reworked. It is currently the blank template from https://github.com/othneildrew/Best-README-Template (2022-11-07). 

Much of it should be deleted.

**Comment by ColtenMikulastik** [comment]
fixed some things on branch "fixing_readme_md", any help would be appreciated.

**Comment by ColtenMikulastik** [comment]
If there are any more changes you feel there should be made let me know! 
Otherwise, feel free to squash and merge the pull request into dev. ***(there are a lot of commits)***

**Comment by ColtenMikulastik** [comment]
It's been a couple of days so I have merged the fixed readme into the dev branch.
